from __future__ import annotations

import json
from datetime import date, datetime, timedelta
from pathlib import Path
from xml.sax.saxutils import escape


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]

INPUT_FILE = REPOSITORY_ROOT / "data" / "contributions.json"
OUTPUT_FILE = REPOSITORY_ROOT / "assets" / "contribution-graph.svg"


CELL_SIZE = 12
CELL_GAP = 4
CELL_STEP = CELL_SIZE + CELL_GAP

LEFT_MARGIN = 52
TOP_MARGIN = 70
RIGHT_MARGIN = 24
BOTTOM_MARGIN = 52

LEVEL_COLORS = {
    0: "#21262d",
    1: "#0e4429",
    2: "#006d32",
    3: "#26a641",
    4: "#39d353",
}


def load_contribution_data() -> dict:
    """Read contribution data generated by fetch_contributions.py."""

    if not INPUT_FILE.exists():
        raise FileNotFoundError(
            f"Contribution data was not found: {INPUT_FILE}\n"
            "Run python scripts\\fetch_contributions.py first."
        )

    with INPUT_FILE.open("r", encoding="utf-8") as file:
        data = json.load(file)

    days = data.get("days")

    if not isinstance(days, list) or not days:
        raise ValueError(
            "The contribution JSON does not contain valid day records."
        )

    return data


def parse_days(raw_days: list[dict]) -> dict[date, dict]:
    """Convert JSON date strings into Python date objects."""

    parsed: dict[date, dict] = {}

    for item in raw_days:
        date_text = item.get("date")

        if not isinstance(date_text, str):
            continue

        try:
            contribution_date = datetime.strptime(
                date_text,
                "%Y-%m-%d",
            ).date()
        except ValueError:
            continue

        try:
            level = int(item.get("level", 0))
        except (TypeError, ValueError):
            level = 0

        try:
            count = int(item.get("count", 0))
        except (TypeError, ValueError):
            count = 0

        parsed[contribution_date] = {
            "level": max(0, min(level, 4)),
            "count": max(0, count),
        }

    if not parsed:
        raise ValueError("No valid contribution dates were found.")

    return parsed


def previous_sunday(value: date) -> date:
    """Return the Sunday on or before the supplied date."""

    days_since_sunday = (value.weekday() + 1) % 7
    return value - timedelta(days=days_since_sunday)


def next_saturday(value: date) -> date:
    """Return the Saturday on or after the supplied date."""

    days_until_saturday = (5 - value.weekday()) % 7
    return value + timedelta(days=days_until_saturday)


def contribution_label(
    contribution_date: date,
    count: int,
) -> str:
    if count == 0:
        activity = "No contributions"
    elif count == 1:
        activity = "1 contribution"
    else:
        activity = f"{count} contributions"

    return (
        f"{activity} on "
        f"{contribution_date.strftime('%B %d, %Y')}"
    )


def build_svg(data: dict) -> str:
    username = str(data.get("username", "GitHub user"))
    parsed_days = parse_days(data["days"])

    first_date = min(parsed_days)
    last_date = max(parsed_days)

    grid_start = previous_sunday(first_date)
    grid_end = next_saturday(last_date)

    number_of_days = (grid_end - grid_start).days + 1
    number_of_weeks = number_of_days // 7

    graph_width = number_of_weeks * CELL_STEP
    width = LEFT_MARGIN + graph_width + RIGHT_MARGIN
    height = TOP_MARGIN + (7 * CELL_STEP) + BOTTOM_MARGIN

    total_contributions = sum(
        int(day["count"]) for day in parsed_days.values()
    )

    cells: list[str] = []

    current_date = grid_start
    animation_index = 0

    while current_date <= grid_end:
        week_index = (current_date - grid_start).days // 7
        day_index = (current_date.weekday() + 1) % 7

        x = LEFT_MARGIN + week_index * CELL_STEP
        y = TOP_MARGIN + day_index * CELL_STEP

        day_data = parsed_days.get(
            current_date,
            {"level": 0, "count": 0},
        )

        level = int(day_data["level"])
        count = int(day_data["count"])

        color = LEVEL_COLORS[level]
        label = escape(
            contribution_label(current_date, count)
        )

        delay = (animation_index % 80) * 0.018
        animation_index += 1

        cells.append(
            f"""
            <rect
                x="{x}"
                y="{y}"
                width="{CELL_SIZE}"
                height="{CELL_SIZE}"
                rx="2"
                fill="{color}"
                opacity="0"
            >
                <title>{label}</title>

                <animate
                    attributeName="opacity"
                    from="0"
                    to="1"
                    dur="0.35s"
                    begin="{delay:.3f}s"
                    fill="freeze"
                />

                <animate
                    attributeName="y"
                    from="{y + 7}"
                    to="{y}"
                    dur="0.35s"
                    begin="{delay:.3f}s"
                    fill="freeze"
                />
            </rect>
            """
        )

        current_date += timedelta(days=1)

    month_labels: list[str] = []
    previous_month: int | None = None

    for week_index in range(number_of_weeks):
        week_date = grid_start + timedelta(weeks=week_index)

        representative_date = week_date + timedelta(days=3)

        if representative_date.month != previous_month:
            x = LEFT_MARGIN + week_index * CELL_STEP

            month_labels.append(
                f"""
                <text
                    x="{x}"
                    y="{TOP_MARGIN - 14}"
                    class="month-label"
                >
                    {representative_date.strftime("%b")}
                </text>
                """
            )

            previous_month = representative_date.month

    weekday_labels = []

    for label, row in [
        ("Mon", 1),
        ("Wed", 3),
        ("Fri", 5),
    ]:
        y = TOP_MARGIN + row * CELL_STEP + 10

        weekday_labels.append(
            f"""
            <text
                x="10"
                y="{y}"
                class="day-label"
            >
                {label}
            </text>
            """
        )

    legend_x = width - 185
    legend_y = height - 22

    legend_cells = []

    for index, level in enumerate(range(5)):
        x = legend_x + 42 + index * CELL_STEP

        legend_cells.append(
            f"""
            <rect
                x="{x}"
                y="{legend_y - 10}"
                width="{CELL_SIZE}"
                height="{CELL_SIZE}"
                rx="2"
                fill="{LEVEL_COLORS[level]}"
            />
            """
        )

    return f"""<svg
    xmlns="http://www.w3.org/2000/svg"
    width="{width}"
    height="{height}"
    viewBox="0 0 {width} {height}"
    role="img"
    aria-label="{escape(username)} GitHub contribution graph"
>
    <style>
        .background {{
            fill: #0d1117;
            stroke: #30363d;
        }}

        .title {{
            fill: #f0f6fc;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI",
                Helvetica, Arial, sans-serif;
            font-size: 17px;
            font-weight: 600;
        }}

        .subtitle {{
            fill: #8b949e;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI",
                Helvetica, Arial, sans-serif;
            font-size: 12px;
        }}

        .month-label,
        .day-label,
        .legend-label {{
            fill: #8b949e;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI",
                Helvetica, Arial, sans-serif;
            font-size: 11px;
        }}
    </style>

    <rect
        class="background"
        x="1"
        y="1"
        width="{width - 2}"
        height="{height - 2}"
        rx="12"
    />

    <text x="18" y="27" class="title">
        {escape(username)}'s contribution activity
    </text>

    <text x="18" y="47" class="subtitle">
        {total_contributions:,} public contributions in the displayed period
    </text>

    {"".join(month_labels)}

    {"".join(weekday_labels)}

    {"".join(cells)}

    <text
        x="{legend_x}"
        y="{legend_y}"
        class="legend-label"
    >
        Less
    </text>

    {"".join(legend_cells)}

    <text
        x="{legend_x + 130}"
        y="{legend_y}"
        class="legend-label"
    >
        More
    </text>
</svg>
"""


def main() -> None:
    data = load_contribution_data()
    svg = build_svg(data)

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(svg, encoding="utf-8")

    print("Animated contribution graph created successfully.")
    print(f"Output: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()